export const movieTypes = {
    GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_FAIL: 'GET_MOVIE_FAIL',
    
    GET_SHOWTIME_REQUEST: 'GET_SHOWTIME_REQUEST',
    GET_SHOWTIME_SUCCESS: 'GET_SHOWTIME_SUCCESS',
    GET_SHOWTIME_FAIL: 'GET_SHOWTIME_FAIL',
}