export const actionTypes = {
  FETCH_CAROUSEL_REQUEST: "FETCH_CAROUSEL_REQUEST",
  FETCH_CAROUSEL_SUCCESS: "FETCH_CAROUSEL_SUCCESS",
  FETCH_CAROUSEL_FAILURE: "FETCH_CAROUSEL_FAILURE",

  FETCH_MOVIES_REQUEST: "FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",

  FETCH_CINEMA_REQUEST: "FETCH_CINEMA_REQUEST",
  FETCH_CINEMA_SUCCESS: "FETCH_CINEMA_SUCCESS",
  FETCH_CINEMA_FAILURE: "FETCH_CINEMA_FAILURE",

  FETCH_CINEMA_TIMES_REQUEST: "FETCH_CINEMA_TIMES_REQUEST",
  FETCH_CINEMA_TIMES_SUCCESS: "FETCH_CINEMA_TIMES_SUCCESS",
  FETCH_CINEMA_TIMES_FAILURE: "FETCH_CINEMA_TIMES_FAILURE",

  FETCH_MOVIE_REQUEST: 'FETCH_MOVIE_REQUEST',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAIL: 'FETCH_MOVIE_FAIL',

  FETCH_SHOWTIME_REQUEST: 'FETCH_SHOWTIME_REQUEST',
  FETCH_SHOWTIME_SUCCESS: 'FETCH_SHOWTIME_SUCCESS',
  FETCH_SHOWTIME_FAIL: 'FETCH_SHOWTIME_FAIL',
};
