
export const movieTypes = {
    GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_FAIL: 'GET_MOVIE_FAIL',
    
    GET_SHOWTIME_REQUEST: 'GET_SHOWTIME_REQUEST',
    GET_SHOWTIME_SUCCESS: 'GET_SHOWTIME_SUCCESS',
    GET_SHOWTIME_FAIL: 'GET_SHOWTIME_FAIL',
}

export const actionTypes = {
  FETCH_CAROUSEL: "FETCH_CAROUSEL",
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_CINEMA: "FETCH_CINEMA",
  FETCH_CINEMA_TIMES: "FETCH_CINEMA_TIMES",
};
